version: "2"

linters:
  default: none
  enable:
    - misspell
    - govet
    - revive
    - ineffassign
    - gomodguard
    - unused
    - staticcheck
  settings:
    staticcheck:
      checks:
        - "all"
        - "-ST1000"
        - "-ST1003"
        - "-ST1005"
        - "-ST1016"
        - "-ST1020"
        - "-ST1021"
        - "-ST1022"
        - "-ST1023"
    misspell:
      locale: US
  exclusions:
    presets: []
    rules:
      - text: "instead of using struct literal"
        linters:
        - revive
      - text: "should have a package comment"
        linters:
          - revive
      - text: "should have comment or be unexported"
        linters:
          - revive
      - text: "time-naming"
        linters:
        - revive
      - text: "error strings should not be capitalized or end with punctuation or a newline"
        linters:
          - revive
          
formatters:
  enable:
    - gofmt
    - goimports
