linters:
  disable-all: true
  enable:
    - typecheck
    - goimports
    - misspell
    - govet
    - revive
    - ineffassign
    - gomodguard
    - gofmt
    - unused

linters-settings:
  golint:
    min-confidence: 0

  misspell:
    locale: US

issues:
  exclude-use-default: false
  exclude:
    - instead of using struct literal
    - should have a package comment
    - should have comment or be unexported
    - time-naming
    - error strings should not be capitalized or end with punctuation or a newline
