version: 2
env:
  - GO111MODULE=on
  - CGO_ENABLED=0

builds:
  - binary: pb
    id: pb
    main: ./main.go
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
      - -tags=kqueue
    ldflags:
      - -s -w -X main.Version=v{{ .Version }} -X main.Commit={{ .ShortCommit }}

archives:
  - name_template: "pb_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "pb_{{ .Version }}_checksums.txt"
